name: RSS Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs once per week
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Universal Set updates
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'UNIVERSALSET'
          feed_list: 'https://universalset.org/feed.xml'
          commit_message: 'Update Universal Set posts'
      - name: Pull Goodreads read
        uses: zwacky/goodreads-profile-workflow@main
        with:
          comment_tag_name: 'GOODREADS-READ'
          goodreads_user_id: '160841838'
          shelf: 'read'
          commit_message: 'Update Goodreads read'
          template: '- $my_rating_stars [$title]($url) by $author'
          sort_by_fields: '>user_read_at'
          max_books_count: '3'
      - name: Pull Goodreads currently reading
        uses: zwacky/goodreads-profile-workflow@main
        with:
          comment_tag_name: 'GOODREADS-CURRENTLY-READING'
          goodreads_user_id: '160841838'
          shelf: 'currently-reading'
          commit_message: 'Update Goodreads currently reading'
          template: '- [$title]($url) by $author ($published_year)'
          sort_by_fields: '>user_date_added'
