name: Sync Goodreads

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly, Sundays at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-reading:
    name: Update README with Goodreads shelves
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull currently reading
        uses: zwacky/goodreads-profile-workflow@v1.2.5
        with:
          comment_tag_name: 'GOODREADS-CURRENTLY-READING'
          goodreads_user_id: '160841838'
          shelf: 'currently-reading'
          template: '- [$title]($url), $author ($published_year)'
          sort_by_fields: '>user_date_added'

      - name: Pull recently read
        uses: zwacky/goodreads-profile-workflow@v1.2.5
        with:
          comment_tag_name: 'GOODREADS-READ'
          goodreads_user_id: '160841838'
          shelf: 'read'
          template: '- [$title]($url) $my_rating_stars'
          sort_by_fields: '>user_read_at'
          max_books_count: '5'
