name: RSS Workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs once per week
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Substack updates
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: 'SUBSTACK'
          feed_list: 'https://universalset.substack.com/feed'
          commit_message: 'Update Substack posts'
          user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
      - name: Pull Goodreads updates
        uses: zwacky/goodreads-profile-workflow@main
        with:
          comment_tag_name: 'GOODREADS'
          goodreads_user_id: '160841838'
          shelf: 'currently-reading'
          commit_message: 'Update Goodreads reading list'
          template: '- [$title]($url) by $author ($published_year)'
